apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-argocd-t-test-west
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/api/v4/projects/47132311/packages/helm/stable
    chart: "managed-argocd"
    targetRevision: 5.3.6
  destination:
    server: https://35.170.75.144:8443
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
