apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-crds-t-test-west
spec:
  project: default
  source:
    repoURL: https://gitlab.com/api/v4/projects/47132210/packages/helm/stable
    chart: "managed-crds"
    targetRevision: 2.4.1
  destination:
    server: https://35.170.75.144:8443
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
